### ISSUE TITLE
jsx instead of tsx why?

### ISSUE THREAD

**Issue by mayankgb** [mannasdev/student-website#1]

**Comment by mayankgb** [comment]
why you using jsx components instead of using tsx components?

**Comment by mannasdev** [comment]
Type errors, couldn't resolve it as it seemed to be an error within next-auth types for some reason, so decided to just use jsx instead of tsx, will change it back once I find a fix

**Comment by mannasdev** [comment]
If you have no issues, can I close this pr ?.
Thanks
